-----------Usuarios

IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='105400685') INSERT INTO Usuarios VALUES('Jaime','Ramirez Rojas','unodostres',GETDATE(),'105400685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='101100685') INSERT INTO Usuarios VALUES('Amanda','Montero Perez','unodosd',GETDATE(),'101100685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='109800685') INSERT INTO Usuarios VALUES('David','Ortiz Higuerey','unodostsa',GETDATE(),'109800685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='105400987') INSERT INTO Usuarios VALUES('Karina','Sanchez Madriz','gatogato',GETDATE(),'105400987',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='105400321') INSERT INTO Usuarios VALUES('Brandon','Blanco Gomez','unodtresaa',GETDATE(),'105400321',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='105400654') INSERT INTO Usuarios VALUES('Valeria','Gonzalez Soto','unodostres',GETDATE(),'105400654',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='105400159') INSERT INTO Usuarios VALUES('Cristian','Castro Garita','unodosseis',GETDATE(),'105400159',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='101470685') INSERT INTO Usuarios VALUES('Rodrigo','Araya Delgado','dostresa',GETDATE(),'101470685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='103570685') INSERT INTO Usuarios VALUES('Sofia','Chaves Mora','unodostres',GETDATE(),'103570685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='107510685') INSERT INTO Usuarios VALUES('Andrea','Campos Mora','unodostres',GETDATE(),'107510685',0)


IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='205400685') INSERT INTO Usuarios VALUES('Ricardo','Villalobos Rojas','unodostres',GETDATE(),'205400685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='201100685') INSERT INTO Usuarios VALUES('Hannah','Salazar Perez','unodosd',GETDATE(),'201100685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='209800685') INSERT INTO Usuarios VALUES('Oscar','Garcia Higuerey','unodostsa',GETDATE(),'209800685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='205400987') INSERT INTO Usuarios VALUES('Belen','Vega Madriz','gatogato',GETDATE(),'205400987',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='205400321') INSERT INTO Usuarios VALUES('Michael','Alfaro Gomez','unodtresaa',GETDATE(),'205400321',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='205400654') INSERT INTO Usuarios VALUES('Fabian','Brenes Soto','unodostres',GETDATE(),'205400654',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='205400159') INSERT INTO Usuarios VALUES('Andres','Gutierrez Garita','unodosseis',GETDATE(),'205400159',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='201470685') INSERT INTO Usuarios VALUES('Barbara','Fernandez Delgado','dostresa',GETDATE(),'201470685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='203570685') INSERT INTO Usuarios VALUES('Angie','Quiros Mora','unodostres',GETDATE(),'203570685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='207510685') INSERT INTO Usuarios VALUES('Nicole','Zuñiga Mora','unodostres',GETDATE(),'207510685',0)


IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='305400685') INSERT INTO Usuarios VALUES('Alejandro','Ramirez Mora','unodostres',GETDATE(),'305400685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='301100685') INSERT INTO Usuarios VALUES('Maria','Hidalgo Perez','unodosd',GETDATE(),'301100685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='309800685') INSERT INTO Usuarios VALUES('Felipe','Ortiz Solano','unodostsa',GETDATE(),'309800685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='305400987') INSERT INTO Usuarios VALUES('Ana','Duran Madriz','gatogato',GETDATE(),'305400987',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='305400321') INSERT INTO Usuarios VALUES('Roberto','Diaz Gomez','unodtresaa',GETDATE(),'305400321',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='305400654') INSERT INTO Usuarios VALUES('Karla','Nuñez Soto','unodostres',GETDATE(),'305400654',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='305400159') INSERT INTO Usuarios VALUES('Miguel','Mora Garita','unodosseis',GETDATE(),'305400159',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='301470685') INSERT INTO Usuarios VALUES('Marta','Chacon Delgado','dostresa',GETDATE(),'301470685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='303570685') INSERT INTO Usuarios VALUES('Tomas','Rivas Mora','unodostres',GETDATE(),'303570685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='307510685') INSERT INTO Usuarios VALUES('Fabiola','ALvarado Mora','unodostres',GETDATE(),'307510685',0)

IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='405400685') INSERT INTO Usuarios VALUES('Alonso','Ramirez Abarca','unodostres',GETDATE(),'405400685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='401100685') INSERT INTO Usuarios VALUES('Daniela','Hidalgo Cascante','unodosd',GETDATE(),'401100685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='409800685') INSERT INTO Usuarios VALUES('Kevin','Ortiz Acuña','unodostsa',GETDATE(),'409800685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='405400987') INSERT INTO Usuarios VALUES('Marcela','Duran Cerdas','gatogato',GETDATE(),'405400987',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='405400321') INSERT INTO Usuarios VALUES('Justin','Diaz Granados','unodtresaa',GETDATE(),'405400321',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='405400654') INSERT INTO Usuarios VALUES('Mariana','Nuñez Guzman','unodostres',GETDATE(),'405400654',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='405400159') INSERT INTO Usuarios VALUES('Manuel','Mora Chinchilla','unodosseis',GETDATE(),'405400159',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='401470685') INSERT INTO Usuarios VALUES('Maripaz','Chacon Arroyo','dostresa',GETDATE(),'401470685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='403570685') INSERT INTO Usuarios VALUES('Esteban','Ramirez Camacho','unodostres',GETDATE(),'403570685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='407510685') INSERT INTO Usuarios VALUES('Laura','Ramirez Flores','unodostres',GETDATE(),'407510685',0)

IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='505400685') INSERT INTO Usuarios VALUES('Dennis','Duran Abarca','unodostres',GETDATE(),'505400685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='501100685') INSERT INTO Usuarios VALUES('Lucia','Leon Cascante','unodosd',GETDATE(),'501100685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='509800685') INSERT INTO Usuarios VALUES('Sergio','Carvajal Acuña','unodostsa',GETDATE(),'509800685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='505400987') INSERT INTO Usuarios VALUES('Gloriana','Blanco Cerdas','gatogato',GETDATE(),'505400987',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='505400321') INSERT INTO Usuarios VALUES('Fernando','Ortiz Granados','unodtresaa',GETDATE(),'505400321',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='505400654') INSERT INTO Usuarios VALUES('Natalia','Bolaños Guzman','unodostres',GETDATE(),'505400654',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='505400159') INSERT INTO Usuarios VALUES('Gabriel','Arguedas Chinchilla','unodosseis',GETDATE(),'505400159',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='501470685') INSERT INTO Usuarios VALUES('Denise','Barquero Arroyo','dostresa',GETDATE(),'501470685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='503570685') INSERT INTO Usuarios VALUES('Mario','Elizondo Camacho','unodostres',GETDATE(),'503570685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='507510685') INSERT INTO Usuarios VALUES('Allison','Sanabria Flores','unodostres',GETDATE(),'507510685',0)

IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='605400685') INSERT INTO Usuarios VALUES('Daniel','Duran Rodriguez','unodostres',GETDATE(),'605400685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='601100685') INSERT INTO Usuarios VALUES('Bianca','Leon Vargas','unodosd',GETDATE(),'601100685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='609800685') INSERT INTO Usuarios VALUES('Jose','Carvajal Jimenez','unodostsa',GETDATE(),'609800685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='605400987') INSERT INTO Usuarios VALUES('Mazel','Blanco Mora','gatogato',GETDATE(),'605400987',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='605400321') INSERT INTO Usuarios VALUES('Juan','Ortiz Rojas','unodtresaa',GETDATE(),'605400321',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='605400654') INSERT INTO Usuarios VALUES('Grettel','Bolaños Gonzalez','unodostres',GETDATE(),'605400654',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='605400159') INSERT INTO Usuarios VALUES('Henry','Arguedas Sanchez','unodosseis',GETDATE(),'605400159',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='601470685') INSERT INTO Usuarios VALUES('Karol','Barquero Hernandez','dostresa',GETDATE(),'601470685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='603570685') INSERT INTO Usuarios VALUES('Ricardo','Elizondo Ramirez','unodostres',GETDATE(),'603570685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='607510685') INSERT INTO Usuarios VALUES('Viviana','Sanabria Castro','unodostres',GETDATE(),'607510685',0)

IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='705400685') INSERT INTO Usuarios VALUES('Marco','Chaves Rodriguez','unodostres',GETDATE(),'705400685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='701100685') INSERT INTO Usuarios VALUES('Valeria','Perez Vargas','unodosd',GETDATE(),'701100685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='709800685') INSERT INTO Usuarios VALUES('Carlos','Morales Jimenez','unodostsa',GETDATE(),'709800685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='705400987') INSERT INTO Usuarios VALUES('Stacy','Campos Mora','gatogato',GETDATE(),'705400987',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='705400321') INSERT INTO Usuarios VALUES('Julian','Quesada Rojas','unodtresaa',GETDATE(),'705400321',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='705400654') INSERT INTO Usuarios VALUES('Skarleth','Piedra Gonzalez','unodostres',GETDATE(),'705400654',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='705400159') INSERT INTO Usuarios VALUES('Emmanuel','Trejos Sanchez','unodosseis',GETDATE(),'705400159',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='701470685') INSERT INTO Usuarios VALUES('Pamela','Campos Hernandez','dostresa',GETDATE(),'701470685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='703570685') INSERT INTO Usuarios VALUES('Anthony','Morales Ramirez','unodostres',GETDATE(),'703570685',0)
IF NOT EXISTS( SELECT U.Cedula FROM Usuarios U WHERE Cedula='707510685') INSERT INTO Usuarios VALUES('Valentina','Quiros Castro','unodostres',GETDATE(),'707510685',0)


-----------Canton a cada usuario


IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=1 and CPU.IdCanton=1) INSERT INTO CantonesPorUsuario VALUES(1,1,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=2 and CPU.IdCanton=2) INSERT INTO CantonesPorUsuario VALUES(2,2,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=3 and CPU.IdCanton=3) INSERT INTO CantonesPorUsuario VALUES(3,3,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=4 and CPU.IdCanton=4) INSERT INTO CantonesPorUsuario VALUES(4,4,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=5 and CPU.IdCanton=5) INSERT INTO CantonesPorUsuario VALUES(5,5,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=6 and CPU.IdCanton=6) INSERT INTO CantonesPorUsuario VALUES(6,6,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=7 and CPU.IdCanton=7) INSERT INTO CantonesPorUsuario VALUES(7,7,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=8 and CPU.IdCanton=8) INSERT INTO CantonesPorUsuario VALUES(8,8,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=9 and CPU.IdCanton=9) INSERT INTO CantonesPorUsuario VALUES(9,9,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=10 and CPU.IdCanton=10) INSERT INTO CantonesPorUsuario VALUES(10,10,GETDATE())

IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=11 and CPU.IdCanton=11) INSERT INTO CantonesPorUsuario VALUES(11,11,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=12 and CPU.IdCanton=12) INSERT INTO CantonesPorUsuario VALUES(12,12,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=13 and CPU.IdCanton=13) INSERT INTO CantonesPorUsuario VALUES(13,13,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=14 and CPU.IdCanton=14) INSERT INTO CantonesPorUsuario VALUES(14,14,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=15 and CPU.IdCanton=15) INSERT INTO CantonesPorUsuario VALUES(15,15,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=16 and CPU.IdCanton=16) INSERT INTO CantonesPorUsuario VALUES(16,16,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=17 and CPU.IdCanton=17) INSERT INTO CantonesPorUsuario VALUES(17,17,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=18 and CPU.IdCanton=18) INSERT INTO CantonesPorUsuario VALUES(18,18,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=19 and CPU.IdCanton=19) INSERT INTO CantonesPorUsuario VALUES(19,19,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=20 and CPU.IdCanton=20) INSERT INTO CantonesPorUsuario VALUES(20,20,GETDATE())

IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=21 and CPU.IdCanton=21) INSERT INTO CantonesPorUsuario VALUES(21,21,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=22 and CPU.IdCanton=1) INSERT INTO CantonesPorUsuario VALUES(22,1,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=23 and CPU.IdCanton=2) INSERT INTO CantonesPorUsuario VALUES(23,2,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=24 and CPU.IdCanton=3) INSERT INTO CantonesPorUsuario VALUES(24,3,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=25 and CPU.IdCanton=4) INSERT INTO CantonesPorUsuario VALUES(25,4,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=26 and CPU.IdCanton=5) INSERT INTO CantonesPorUsuario VALUES(26,5,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=27 and CPU.IdCanton=6) INSERT INTO CantonesPorUsuario VALUES(27,6,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=28 and CPU.IdCanton=7) INSERT INTO CantonesPorUsuario VALUES(28,7,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=29 and CPU.IdCanton=8) INSERT INTO CantonesPorUsuario VALUES(29,8,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=30 and CPU.IdCanton=9) INSERT INTO CantonesPorUsuario VALUES(30,9,GETDATE())

IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=31 and CPU.IdCanton=10) INSERT INTO CantonesPorUsuario VALUES(31,10,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=32 and CPU.IdCanton=11) INSERT INTO CantonesPorUsuario VALUES(32,11,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=33 and CPU.IdCanton=12) INSERT INTO CantonesPorUsuario VALUES(33,12,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=34 and CPU.IdCanton=13) INSERT INTO CantonesPorUsuario VALUES(34,13,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=35 and CPU.IdCanton=14) INSERT INTO CantonesPorUsuario VALUES(35,14,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=36 and CPU.IdCanton=15) INSERT INTO CantonesPorUsuario VALUES(36,15,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=37 and CPU.IdCanton=16) INSERT INTO CantonesPorUsuario VALUES(37,16,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=38 and CPU.IdCanton=17) INSERT INTO CantonesPorUsuario VALUES(38,17,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=39 and CPU.IdCanton=18) INSERT INTO CantonesPorUsuario VALUES(39,18,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=40 and CPU.IdCanton=19) INSERT INTO CantonesPorUsuario VALUES(40,19,GETDATE())

IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=41 and CPU.IdCanton=20) INSERT INTO CantonesPorUsuario VALUES(41,20,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=42 and CPU.IdCanton=21) INSERT INTO CantonesPorUsuario VALUES(42,21,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=43 and CPU.IdCanton=1) INSERT INTO CantonesPorUsuario VALUES(43,1,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=44 and CPU.IdCanton=2) INSERT INTO CantonesPorUsuario VALUES(44,2,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=45 and CPU.IdCanton=3) INSERT INTO CantonesPorUsuario VALUES(45,3,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=46 and CPU.IdCanton=4) INSERT INTO CantonesPorUsuario VALUES(46,4,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=47 and CPU.IdCanton=5) INSERT INTO CantonesPorUsuario VALUES(47,5,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=48 and CPU.IdCanton=6) INSERT INTO CantonesPorUsuario VALUES(48,6,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=49 and CPU.IdCanton=7) INSERT INTO CantonesPorUsuario VALUES(49,7,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=50 and CPU.IdCanton=8) INSERT INTO CantonesPorUsuario VALUES(50,8,GETDATE())

IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=51 and CPU.IdCanton=9) INSERT INTO CantonesPorUsuario VALUES(51,9,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=52 and CPU.IdCanton=10) INSERT INTO CantonesPorUsuario VALUES(52,10,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=53 and CPU.IdCanton=11) INSERT INTO CantonesPorUsuario VALUES(53,11,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=54 and CPU.IdCanton=12) INSERT INTO CantonesPorUsuario VALUES(54,12,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=55 and CPU.IdCanton=13) INSERT INTO CantonesPorUsuario VALUES(55,13,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=56 and CPU.IdCanton=14) INSERT INTO CantonesPorUsuario VALUES(56,14,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=57 and CPU.IdCanton=15) INSERT INTO CantonesPorUsuario VALUES(57,15,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=58 and CPU.IdCanton=16) INSERT INTO CantonesPorUsuario VALUES(58,16,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=59 and CPU.IdCanton=17) INSERT INTO CantonesPorUsuario VALUES(59,17,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=60 and CPU.IdCanton=18) INSERT INTO CantonesPorUsuario VALUES(60,18,GETDATE())

IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=61 and CPU.IdCanton=19) INSERT INTO CantonesPorUsuario VALUES(61,19,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=62 and CPU.IdCanton=20) INSERT INTO CantonesPorUsuario VALUES(62,20,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=63 and CPU.IdCanton=21) INSERT INTO CantonesPorUsuario VALUES(63,21,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=64 and CPU.IdCanton=1) INSERT INTO CantonesPorUsuario VALUES(64,1,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=65 and CPU.IdCanton=2) INSERT INTO CantonesPorUsuario VALUES(65,2,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=66 and CPU.IdCanton=3) INSERT INTO CantonesPorUsuario VALUES(66,3,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=67 and CPU.IdCanton=4) INSERT INTO CantonesPorUsuario VALUES(67,4,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=68 and CPU.IdCanton=5) INSERT INTO CantonesPorUsuario VALUES(68,5,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=69 and CPU.IdCanton=6) INSERT INTO CantonesPorUsuario VALUES(69,6,GETDATE())
IF NOT EXISTS( SELECT IdUsuario FROM CantonesPorUsuario as CPU WHERE CPU.IdUsuario=70 and CPU.IdCanton=7) INSERT INTO CantonesPorUsuario VALUES(70,7,GETDATE())


----------Puntuaciones

DECLARE @Inicio INT = 1

WHILE(@Inicio<=70)
BEGIN
	EXEC dbo.Califica @Usuario = @Inicio
	SET @Inicio = @Inicio +1
END


